################################################
# Moveit control settings ######################
################################################
# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: panda_arm
  joint_model_group_pose: ready
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
    - panda_finger_joint1
  sim_control_mode: 1 # 0: position, 1: velocity
################################################
# Controllers used with the Simulated robot #####
################################################

#######################################
# ROS control default controllers #####
#######################################

# Joint position trajectory controller
position_joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
  constraints:
    goal_time: 0.5
    panda_joint1:
      goal: 0.05
    panda_joint2:
      goal: 0.05
    panda_joint3:
      goal: 0.05
    panda_joint4:
      goal: 0.05
    panda_joint5:
      goal: 0.05
    panda_joint6:
      goal: 0.05
    panda_joint7:
      goal: 0.05
  state_publish_rate: 100

# Joint effort trajectory controller
effort_joint_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
  constraints:
    goal_time: 0.5
    panda_joint1:
      goal: 0.05
    panda_joint2:
      goal: 0.05
    panda_joint3:
      goal: 0.05
    panda_joint4:
      goal: 0.05
    panda_joint5:
      goal: 0.05
    panda_joint6:
      goal: 0.05
    panda_joint7:
      goal: 0.05
  gains:
    panda_joint1: { p: 12000, d: 50, i: 0.0, i_clamp: 10000 }
    panda_joint2: { p: 30000, d: 100, i: 0.02, i_clamp: 10000 }
    panda_joint3: { p: 18000, d: 50, i: 0.01, i_clamp: 1 }
    panda_joint4: { p: 18000, d: 70, i: 0.01, i_clamp: 10000 }
    panda_joint5: { p: 12000, d: 70, i: 0.01, i_clamp: 1 }
    panda_joint6: { p: 7000, d: 50, i: 0.01, i_clamp: 1 }
    panda_joint7: { p: 2000, d: 20, i: 0.0, i_clamp: 1 }

# Joint position controllers
panda_arm_joint1_position_controller:
  type: position_controllers/JointPositionController
  joint: panda_joint1
panda_arm_joint2_position_controller:
  type: position_controllers/JointPositionController
  joint: panda_joint2
panda_arm_joint3_position_controller:
  type: position_controllers/JointPositionController
  joint: panda_joint3
panda_arm_joint4_position_controller:
  type: position_controllers/JointPositionController
  joint: panda_joint4
panda_arm_joint5_position_controller:
  type: position_controllers/JointPositionController
  joint: panda_joint5
panda_arm_joint6_position_controller:
  type: position_controllers/JointPositionController
  joint: panda_joint6
panda_arm_joint7_position_controller:
  type: position_controllers/JointPositionController
  joint: panda_joint7

# Joint effort controllers
panda_arm_joint1_effort_controller:
  type: effort_controllers/JointEffortController
  joint: panda_joint1
panda_arm_joint2_effort_controller:
  type: effort_controllers/JointEffortController
  joint: panda_joint2
panda_arm_joint3_effort_controller:
  type: effort_controllers/JointEffortController
  joint: panda_joint3
panda_arm_joint4_effort_controller:
  type: effort_controllers/JointEffortController
  joint: panda_joint4
panda_arm_joint5_effort_controller:
  type: effort_controllers/JointEffortController
  joint: panda_joint5
panda_arm_joint6_effort_controller:
  type: effort_controllers/JointEffortController
  joint: panda_joint6
panda_arm_joint7_effort_controller:
  type: effort_controllers/JointEffortController
  joint: panda_joint7

# General gazebo_ros_control PID gains
# NOTE: See https://github.com/ros-simulation/gazebo_ros_pkgs/pull/135 for why this is needed.
gazebo_ros_control:
  pid_gains:
    panda_joint1: { p: 12000, d: 50, i: 0.0, i_clamp: 10000 }
    panda_joint2: { p: 30000, d: 100, i: 0.02, i_clamp: 10000 }
    panda_joint3: { p: 18000, d: 50, i: 0.01, i_clamp: 1 }
    panda_joint4: { p: 18000, d: 70, i: 0.01, i_clamp: 10000 }
    panda_joint5: { p: 12000, d: 70, i: 0.01, i_clamp: 1 }
    panda_joint6: { p: 7000, d: 50, i: 0.01, i_clamp: 1 }
    panda_joint7: { p: 2000, d: 20, i: 0.0, i_clamp: 1 }
