################################################
# Moveit control settings ######################
################################################
# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: panda_arm
  joint_model_group_pose: ready
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
    - panda_finger_joint1
  sim_control_mode: 1 # 0: position, 1: velocity
################################################
# Controllers used with the Real robot #########
################################################

#######################################
# ROS control default controllers #####
#######################################

# Joint position trajectory controller
position_joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
  constraints:
    goal_time: 0.5
    panda_joint1:
      goal: 0.05
    panda_joint2:
      goal: 0.05
    panda_joint3:
      goal: 0.05
    panda_joint4:
      goal: 0.05
    panda_joint5:
      goal: 0.05
    panda_joint6:
      goal: 0.05
    panda_joint7:
      goal: 0.05

# Joint effort trajectory controller
effort_joint_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
  constraints:
    goal_time: 0.5
    panda_joint1:
      goal: 0.05
    panda_joint2:
      goal: 0.05
    panda_joint3:
      goal: 0.05
    panda_joint4:
      goal: 0.05
    panda_joint5:
      goal: 0.05
    panda_joint6:
      goal: 0.05
    panda_joint7:
      goal: 0.05

# Joint position controllers
panda_arm_joint1_position_controller:
  type: position_controllers/JointPositionController
  joint: panda_joint1
panda_arm_joint2_position_controller:
  type: position_controllers/JointPositionController
  joint: panda_joint2
panda_arm_joint3_position_controller:
  type: position_controllers/JointPositionController
  joint: panda_joint3
panda_arm_joint4_position_controller:
  type: position_controllers/JointPositionController
  joint: panda_joint4
panda_arm_joint5_position_controller:
  type: position_controllers/JointPositionController
  joint: panda_joint5
panda_arm_joint6_position_controller:
  type: position_controllers/JointPositionController
  joint: panda_joint6
panda_arm_joint7_position_controller:
  type: position_controllers/JointPositionController
  joint: panda_joint7
# Joint group position controller
panda_arm_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7

# Joint effort controllers
panda_arm_joint1_effort_controller:
  type: effort_controllers/JointEffortController
  joint: panda_joint1
panda_arm_joint2_effort_controller:
  type: effort_controllers/JointEffortController
  joint: panda_joint2
panda_arm_joint3_effort_controller:
  type: effort_controllers/JointEffortController
  joint: panda_joint3
panda_arm_joint4_effort_controller:
  type: effort_controllers/JointEffortController
  joint: panda_joint4
panda_arm_joint5_effort_controller:
  type: effort_controllers/JointEffortController
  joint: panda_joint5
panda_arm_joint6_effort_controller:
  type: effort_controllers/JointEffortController
  joint: panda_joint6
panda_arm_joint7_effort_controller:
  type: effort_controllers/JointEffortController
  joint: panda_joint7

# Joint group effort controller
panda_arm_effort_controller:
  type: effort_controllers/JointGroupEffortController
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7

#######################################
# ROS control custom controllers ######
#######################################
# NOTE: Custom controllers that were based on the franka_example_controllers
joint_position_example_controller:
  type: real_panda_control_examples/JointPositionExampleController
  joint_names:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7

force_example_controller:
  type: real_panda_control_examples/ForceExampleController
  arm_id: panda
  joint_names:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
